name: NetDeck Release

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:
  build_plugin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup latest Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Setup PNPM@10
        uses: pnpm/action-setup@v4
        with:
          version: "10.11.0"

      - name: Sync version from VERSION file
        run: |
          if [ -f "VERSION" ]; then
            chmod +x update-version.sh
            ./update-version.sh
            echo "Version synchronized from VERSION file"
          else
            echo "VERSION file not found, using existing versions"
          fi

      - name: Build NetDeck frontend from source
        run: |
          pnpm install --frozen-lockfile
          pnpm run build
        continue-on-error: true

      - name: Download Decky Plugin CLI
        run: |
          mkdir $(pwd)/cli
          curl -L -o $(pwd)/cli/decky "https://github.com/SteamDeckHomebrew/cli/releases/latest/download/decky-linux-x86_64"
          chmod +x $(pwd)/cli/decky

      - name: Build NetDeck plugin
        run: |
          $(pwd)/cli/decky plugin build $(pwd)

      - name: Show NetDeck build files
        run: |
          ls out/NetDeck.zip
          7z l out/NetDeck.zip

      - name: Publish NetDeck Artifact
        uses: actions/upload-artifact@v4
        with:
          name: NetDeck
          path: out/NetDeck.zip

  publish:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    needs: build_plugin
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - run: mkdir /tmp/artifacts

      - name: Download NetDeck artifact
        uses: actions/download-artifact@v4
        with:
          path: /tmp/artifacts

      - run: ls -R /tmp/artifacts

      - name: Get version from tag
        id: get_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Version: $VERSION"

      - name: Publish NetDeck to GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            /tmp/artifacts/NetDeck/NetDeck.zip
          tag_name: ${{ github.ref_name }}
          name: "NetDeck v${{ steps.get_version.outputs.version }}"
          body: |
            # NetDeck v${{ steps.get_version.outputs.version }}
            
            Advanced networking plugin for Steam Deck and handheld PCs.
            
            ## Features
            - MAC address spoofing for bypassing network restrictions
            - WiFi hotspot creation with dual-adapter support
            - Internet sharing through NAT bridging
            - Hidden SSID support for privacy
            - Secure credential generation with anonymous SSIDs
            - Connected client monitoring and management
            
            ## Installation
            1. Download `NetDeck.zip` below
            2. Extract to your Decky plugins directory: `/home/deck/homebrew/plugins/NetDeck/`
            3. Restart Decky Loader
            
            ## Compatible Devices
            - Most devices running SteamOS
            
            ## Requirements
            - Two WiFi adapters (built-in + USB adapter recommended)
            - NetworkManager for connection management
            - Root permissions for network configuration
            
          draft: false
          generate_release_notes: false
          prerelease: contains(github.ref, 'pre')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}